# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lati', models.FloatField()),
                ('longi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('vacancy', models.IntegerField()),
                ('up_time', models.DateTimeField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Parking')),
            ],
        ),
    ]
