# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Location.Parking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
