# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vac',
            fields=[
                ('gsm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parking_id', models.IntegerField()),
                ('vacancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('gsm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vacancy', models.IntegerField()),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Parking')),
            ],
        ),
    ]
