# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=50)),
                ('parkingName', models.CharField(max_length=50)),
                ('vacany', models.IntegerField()),
                ('lati', models.FloatField()),
                ('longi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('Mum', 'Mumbai'), ('Lko', 'Lucknow')], max_length=1)),
            ],
        ),
    ]
