# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=50)),
                ('parking_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Mum', 'Mumbai'), ('Lko', 'Lucknow')], max_length=3)),
            ],
        ),
    ]
