# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170109_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='vacany',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='lati',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='longi',
            new_name='long',
        ),
    ]
